"""Shared classification and retry constants."""

from __future__ import annotations

CLASSIFICATION_TYPE_SUBMISSION_REVIEW = "submission_review"

CATEGORY_VALID_PROFILE_CANDIDATE = "valid_profile_candidate"
CATEGORY_INVALID_FILE = "invalid_file"
CATEGORY_UNSUPPORTED_IMAGE_TYPE = "unsupported_image_type"
CATEGORY_SUSPICIOUS_FILE = "suspicious_file"
CATEGORY_LOW_QUALITY_IMAGE = "low_quality_image"
CATEGORY_INCOMPLETE_METADATA = "incomplete_metadata"
CATEGORY_NON_PROFILE_IMAGE = "non_profile_image"
CATEGORY_UNSAFE_CONTENT = "unsafe_content"

CLASSIFICATION_CATEGORIES = (
    CATEGORY_VALID_PROFILE_CANDIDATE,
    CATEGORY_INVALID_FILE,
    CATEGORY_UNSUPPORTED_IMAGE_TYPE,
    CATEGORY_SUSPICIOUS_FILE,
    CATEGORY_LOW_QUALITY_IMAGE,
    CATEGORY_INCOMPLETE_METADATA,
    CATEGORY_NON_PROFILE_IMAGE,
    CATEGORY_UNSAFE_CONTENT,
)

CATEGORY_PRIORITY = (
    CATEGORY_INVALID_FILE,
    CATEGORY_UNSUPPORTED_IMAGE_TYPE,
    CATEGORY_SUSPICIOUS_FILE,
    CATEGORY_UNSAFE_CONTENT,
    CATEGORY_INCOMPLETE_METADATA,
    CATEGORY_LOW_QUALITY_IMAGE,
    CATEGORY_NON_PROFILE_IMAGE,
    CATEGORY_VALID_PROFILE_CANDIDATE,
)

DECISION_PASSES_AUTOMATED_CHECKS = "passes_automated_checks"
DECISION_FAILS_AUTOMATED_CHECKS = "fails_automated_checks"
DECISION_NEEDS_MANUAL_REVIEW = "needs_manual_review"

REVIEW_DECISIONS = (
    DECISION_PASSES_AUTOMATED_CHECKS,
    DECISION_FAILS_AUTOMATED_CHECKS,
    DECISION_NEEDS_MANUAL_REVIEW,
)

PROVIDER_RULE_BASED = "rule_based"
PROVIDER_MODEL = "model"
CLASSIFIER_PROVIDERS = (PROVIDER_RULE_BASED, PROVIDER_MODEL)

SUBMISSION_STATUS_PENDING_CLASSIFICATION = "pending_classification"
SUBMISSION_STATUS_CLASSIFYING = "classifying"
SUBMISSION_STATUS_CLASSIFIED = "classified"
SUBMISSION_STATUS_NEEDS_MANUAL_REVIEW = "needs_manual_review"
SUBMISSION_STATUS_REJECTED = "rejected"
SUBMISSION_STATUS_CLASSIFICATION_FAILED = "classification_failed"

SUBMISSION_STATUSES = (
    SUBMISSION_STATUS_PENDING_CLASSIFICATION,
    SUBMISSION_STATUS_CLASSIFYING,
    SUBMISSION_STATUS_CLASSIFIED,
    SUBMISSION_STATUS_NEEDS_MANUAL_REVIEW,
    SUBMISSION_STATUS_REJECTED,
    SUBMISSION_STATUS_CLASSIFICATION_FAILED,
)

TERMINAL_SUBMISSION_STATUSES = (
    SUBMISSION_STATUS_CLASSIFIED,
    SUBMISSION_STATUS_NEEDS_MANUAL_REVIEW,
    SUBMISSION_STATUS_REJECTED,
    SUBMISSION_STATUS_CLASSIFICATION_FAILED,
)

PUBLISH_STATUS_PENDING = "pending"
PUBLISH_STATUS_PUBLISHING = "publishing"
PUBLISH_STATUS_PUBLISHED = "published"
PUBLISH_STATUS_RETRY_SCHEDULED = "publish_retry_scheduled"
PUBLISH_STATUS_FAILED = "publish_failed"

JOB_PUBLISH_STATUSES = (
    PUBLISH_STATUS_PENDING,
    PUBLISH_STATUS_PUBLISHING,
    PUBLISH_STATUS_PUBLISHED,
    PUBLISH_STATUS_RETRY_SCHEDULED,
    PUBLISH_STATUS_FAILED,
)

JOB_PUBLISH_STATUS_TRANSITIONS = {
    PUBLISH_STATUS_PENDING: (PUBLISH_STATUS_PUBLISHING, PUBLISH_STATUS_RETRY_SCHEDULED),
    PUBLISH_STATUS_PUBLISHING: (
        PUBLISH_STATUS_PUBLISHED,
        PUBLISH_STATUS_RETRY_SCHEDULED,
        PUBLISH_STATUS_FAILED,
    ),
    PUBLISH_STATUS_RETRY_SCHEDULED: (PUBLISH_STATUS_PUBLISHING, PUBLISH_STATUS_FAILED),
    PUBLISH_STATUS_PUBLISHED: (),
    PUBLISH_STATUS_FAILED: (),
}

RABBITMQ_PUBLISH_MAX_ATTEMPTS = 3
WORKER_CLASSIFIER_MAX_RETRIES = 3
CLASSIFIER_REQUEST_TIMEOUT_SECONDS = 5
RETRY_BACKOFF_BASE_SECONDS = 2
RETRY_BACKOFF_CAP_SECONDS = 60

CLASSIFIER_VERSION = "rules-v1"
CLASSIFICATION_SCHEMA_VERSION = "classification-result-v1"
