apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: photo-classification
spec:
  type: ClusterIP
  selector:
    app: classifier
  ports:
    - name: http
      port: 8001
      targetPort: http
