apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-http
  namespace: photo-classification
spec:
  rules:
    - host: photo-classification.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  name: http
